In [82]:
import numpy as np
import matplotlib.pyplot as plt
import biotite.sequence as seq
import biotite.sequence.align as align
import biotite.sequence.phylo as phylo
import biotite.sequence.graphics as graphics

# Obtain BLOSUM62
matrix = align.SubstitutionMatrix.std_protein_matrix()
print(matrix)

    A   C   D   E   F   G   H   I   K   L   M   N   P   Q   R   S   T   V   W   Y   B   Z   X   *
A   4   0  -2  -1  -2   0  -2  -1  -1  -1  -1  -2  -1  -1  -1   1   0   0  -3  -2  -2  -1   0  -4
C   0   9  -3  -4  -2  -3  -3  -1  -3  -1  -1  -3  -3  -3  -3  -1  -1  -1  -2  -2  -3  -3  -2  -4
D  -2  -3   6   2  -3  -1  -1  -3  -1  -4  -3   1  -1   0  -2   0  -1  -3  -4  -3   4   1  -1  -4
E  -1  -4   2   5  -3  -2   0  -3   1  -3  -2   0  -1   2   0   0  -1  -2  -3  -2   1   4  -1  -4
F  -2  -2  -3  -3   6  -3  -1   0  -3   0   0  -3  -4  -3  -3  -2  -2  -1   1   3  -3  -3  -1  -4
G   0  -3  -1  -2  -3   6  -2  -4  -2  -4  -3   0  -2  -2  -2   0  -2  -3  -2  -3  -1  -2  -1  -4
H  -2  -3  -1   0  -1  -2   8  -3  -1  -3  -2   1  -2   0   0  -1  -2  -3  -2   2   0   0  -1  -4
I  -1  -1  -3  -3   0  -4  -3   4  -3   2   1  -3  -3  -3  -3  -2  -1   3  -3  -1  -3  -3  -1  -4
K  -1  -3  -1   1  -3  -2  -1  -3   5  -2  -1   0  -1   1   2   0  -1  -2  -3  -2   0   1  -1  -4
L  -1  -1  -4  -3   

In [38]:
#matrix = align.SubstitutionMatrix(
#    seq.Alphabet(matrix.get_alphabet1().get_symbols()[:-4]),
#    seq.Alphabet(matrix.get_alphabet2().get_symbols()[:-4]),
#    matrix.score_matrix()[:-4, :-4]
#)
similarities = matrix.score_matrix()
print(matrix)
list(matrix.get_alphabet1())

    A   C   D   E   F   G   H   I   K   L   M   N   P   Q   R   S   T   V   W   Y   B   Z   X   *
A   4   0  -2  -1  -2   0  -2  -1  -1  -1  -1  -2  -1  -1  -1   1   0   0  -3  -2  -2  -1   0  -4
C   0   9  -3  -4  -2  -3  -3  -1  -3  -1  -1  -3  -3  -3  -3  -1  -1  -1  -2  -2  -3  -3  -2  -4
D  -2  -3   6   2  -3  -1  -1  -3  -1  -4  -3   1  -1   0  -2   0  -1  -3  -4  -3   4   1  -1  -4
E  -1  -4   2   5  -3  -2   0  -3   1  -3  -2   0  -1   2   0   0  -1  -2  -3  -2   1   4  -1  -4
F  -2  -2  -3  -3   6  -3  -1   0  -3   0   0  -3  -4  -3  -3  -2  -2  -1   1   3  -3  -3  -1  -4
G   0  -3  -1  -2  -3   6  -2  -4  -2  -4  -3   0  -2  -2  -2   0  -2  -3  -2  -3  -1  -2  -1  -4
H  -2  -3  -1   0  -1  -2   8  -3  -1  -3  -2   1  -2   0   0  -1  -2  -3  -2   2   0   0  -1  -4
I  -1  -1  -3  -3   0  -4  -3   4  -3   2   1  -3  -3  -3  -3  -2  -1   3  -3  -1  -3  -3  -1  -4
K  -1  -3  -1   1  -3  -2  -1  -3   5  -2  -1   0  -1   1   2   0  -1  -2  -3  -2   0   1  -1  -4
L  -1  -1  -4  -3   

['A',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'K',
 'L',
 'M',
 'N',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'V',
 'W',
 'Y',
 'B',
 'Z',
 'X',
 '*']

In [40]:
def get_distance(similarities, i, j):
    s_max = (similarities[i,i] + similarities[j,j]) / 2
    return s_max - similarities[i,j]

distances = np.zeros(similarities.shape)
for i in range(distances.shape[0]):
    for j in range(distances.shape[1]):
        distances[i,j] = get_distance(similarities, i, j)

In [25]:
print(distances)

[[ 0.   6.5  7.   5.5  7.   5.   8.   5.   5.5  5.   5.5  7.   6.5  5.5
   5.5  3.   4.5  4.  10.5  7.5  6.   5.   1.5  6.5]
 [ 6.5  0.  10.5 11.   9.5 10.5 11.5  7.5 10.   7.5  8.  10.5 11.  10.
  10.   7.5  8.   7.5 12.  10.   9.5  9.5  6.   9. ]
 [ 7.  10.5  0.   3.5  9.   7.   8.   8.   6.5  9.   8.5  5.   7.5  5.5
   7.5  5.   6.5  8.  12.5  9.5  1.   4.   3.5  7.5]
 [ 5.5 11.   3.5  0.   8.5  7.5  6.5  7.5  4.   7.5  7.   5.5  7.   3.
   5.   4.5  6.   6.5 11.   8.   3.5  0.5  3.   7. ]
 [ 7.   9.5  9.   8.5  0.   9.   8.   5.   8.5  5.   5.5  9.  10.5  8.5
   8.5  7.   7.5  6.   7.5  3.5  8.   8.   3.5  7.5]
 [ 5.  10.5  7.   7.5  9.   0.   9.   9.   7.5  9.   8.5  6.   8.5  7.5
   7.5  5.   7.5  8.  10.5  9.5  6.   7.   3.5  7.5]
 [ 8.  11.5  8.   6.5  8.   9.   0.   9.   7.5  9.   8.5  6.   9.5  6.5
   6.5  7.   8.5  9.  11.5  5.5  6.   6.   4.5  8.5]
 [ 5.   7.5  8.   7.5  5.   9.   9.   0.   7.5  2.   3.5  8.   8.5  7.5
   7.5  6.   5.5  1.  10.5  6.5  7.   7.   2.5  6.5]
 [

In [26]:
print(similarities)
print(distances.shape)
get_distance(similarities, 0, 1)

[[ 4  0 -2 -1 -2  0 -2 -1 -1 -1 -1 -2 -1 -1 -1  1  0  0 -3 -2 -2 -1  0 -4]
 [ 0  9 -3 -4 -2 -3 -3 -1 -3 -1 -1 -3 -3 -3 -3 -1 -1 -1 -2 -2 -3 -3 -2 -4]
 [-2 -3  6  2 -3 -1 -1 -3 -1 -4 -3  1 -1  0 -2  0 -1 -3 -4 -3  4  1 -1 -4]
 [-1 -4  2  5 -3 -2  0 -3  1 -3 -2  0 -1  2  0  0 -1 -2 -3 -2  1  4 -1 -4]
 [-2 -2 -3 -3  6 -3 -1  0 -3  0  0 -3 -4 -3 -3 -2 -2 -1  1  3 -3 -3 -1 -4]
 [ 0 -3 -1 -2 -3  6 -2 -4 -2 -4 -3  0 -2 -2 -2  0 -2 -3 -2 -3 -1 -2 -1 -4]
 [-2 -3 -1  0 -1 -2  8 -3 -1 -3 -2  1 -2  0  0 -1 -2 -3 -2  2  0  0 -1 -4]
 [-1 -1 -3 -3  0 -4 -3  4 -3  2  1 -3 -3 -3 -3 -2 -1  3 -3 -1 -3 -3 -1 -4]
 [-1 -3 -1  1 -3 -2 -1 -3  5 -2 -1  0 -1  1  2  0 -1 -2 -3 -2  0  1 -1 -4]
 [-1 -1 -4 -3  0 -4 -3  2 -2  4  2 -3 -3 -2 -2 -2 -1  1 -2 -1 -4 -3 -1 -4]
 [-1 -1 -3 -2  0 -3 -2  1 -1  2  5 -2 -2  0 -1 -1 -1  1 -1 -1 -3 -1 -1 -4]
 [-2 -3  1  0 -3  0  1 -3  0 -3 -2  6 -2  0  0  1  0 -3 -4 -2  3  0 -1 -4]
 [-1 -3 -1 -1 -4 -2 -2 -3 -1 -3 -2 -2  7 -1 -2 -1 -1 -2 -4 -3 -2 -1 -2 -4]
 [-1 -3  0  2 -3 -2  0 -3

6.5

In [43]:
aas = list(matrix.get_alphabet1())
blosum62_dict = {}
for index_row, aa in enumerate(aas):
    for index_col, value in enumerate(distances[index_row]):
        blosum62_dict[(aa, aas[index_col])] = value
print(blosum62_dict)

{('A', 'A'): 0.0, ('A', 'C'): 6.5, ('A', 'D'): 7.0, ('A', 'E'): 5.5, ('A', 'F'): 7.0, ('A', 'G'): 5.0, ('A', 'H'): 8.0, ('A', 'I'): 5.0, ('A', 'K'): 5.5, ('A', 'L'): 5.0, ('A', 'M'): 5.5, ('A', 'N'): 7.0, ('A', 'P'): 6.5, ('A', 'Q'): 5.5, ('A', 'R'): 5.5, ('A', 'S'): 3.0, ('A', 'T'): 4.5, ('A', 'V'): 4.0, ('A', 'W'): 10.5, ('A', 'Y'): 7.5, ('A', 'B'): 6.0, ('A', 'Z'): 5.0, ('A', 'X'): 1.5, ('A', '*'): 6.5, ('C', 'A'): 6.5, ('C', 'C'): 0.0, ('C', 'D'): 10.5, ('C', 'E'): 11.0, ('C', 'F'): 9.5, ('C', 'G'): 10.5, ('C', 'H'): 11.5, ('C', 'I'): 7.5, ('C', 'K'): 10.0, ('C', 'L'): 7.5, ('C', 'M'): 8.0, ('C', 'N'): 10.5, ('C', 'P'): 11.0, ('C', 'Q'): 10.0, ('C', 'R'): 10.0, ('C', 'S'): 7.5, ('C', 'T'): 8.0, ('C', 'V'): 7.5, ('C', 'W'): 12.0, ('C', 'Y'): 10.0, ('C', 'B'): 9.5, ('C', 'Z'): 9.5, ('C', 'X'): 6.0, ('C', '*'): 9.0, ('D', 'A'): 7.0, ('D', 'C'): 10.5, ('D', 'D'): 0.0, ('D', 'E'): 3.5, ('D', 'F'): 9.0, ('D', 'G'): 7.0, ('D', 'H'): 8.0, ('D', 'I'): 8.0, ('D', 'K'): 6.5, ('D', 'L'): 9.0, 

In [112]:
dist_with_gap_penalty = np.empty((0, len(distances[0]) + 1), int)
for row in distances:
    row = list(np.append(row, distances.max()))
    dist_with_gap_penalty = np.append(dist_with_gap_penalty, np.array([row]), axis=0)

indel_row = np.append(np.array([[distances.max()] * len(distances[0])]), 0)
dist_with_gap_penalty = np.append(dist_with_gap_penalty, np.array([indel_row]), 
                                  axis=0)
dist_with_gap_penalty

array([[ 0. ,  6.5,  7. ,  5.5,  7. ,  5. ,  8. ,  5. ,  5.5,  5. ,  5.5,
         7. ,  6.5,  5.5,  5.5,  3. ,  4.5,  4. , 10.5,  7.5,  6. ,  5. ,
         1.5,  6.5, 13. ],
       [ 6.5,  0. , 10.5, 11. ,  9.5, 10.5, 11.5,  7.5, 10. ,  7.5,  8. ,
        10.5, 11. , 10. , 10. ,  7.5,  8. ,  7.5, 12. , 10. ,  9.5,  9.5,
         6. ,  9. , 13. ],
       [ 7. , 10.5,  0. ,  3.5,  9. ,  7. ,  8. ,  8. ,  6.5,  9. ,  8.5,
         5. ,  7.5,  5.5,  7.5,  5. ,  6.5,  8. , 12.5,  9.5,  1. ,  4. ,
         3.5,  7.5, 13. ],
       [ 5.5, 11. ,  3.5,  0. ,  8.5,  7.5,  6.5,  7.5,  4. ,  7.5,  7. ,
         5.5,  7. ,  3. ,  5. ,  4.5,  6. ,  6.5, 11. ,  8. ,  3.5,  0.5,
         3. ,  7. , 13. ],
       [ 7. ,  9.5,  9. ,  8.5,  0. ,  9. ,  8. ,  5. ,  8.5,  5. ,  5.5,
         9. , 10.5,  8.5,  8.5,  7. ,  7.5,  6. ,  7.5,  3.5,  8. ,  8. ,
         3.5,  7.5, 13. ],
       [ 5. , 10.5,  7. ,  7.5,  9. ,  0. ,  9. ,  9. ,  7.5,  9. ,  8.5,
         6. ,  8.5,  7.5,  7.5,  5. ,  7.5,  8. , 1